In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import tree

#load dataset
dx=pd.read_csv(r"C:\Users\ADMIN\Desktop\data science git\IRIS.csv")
dx

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
#the length of the dataset
print(len(dx))

150


In [10]:
#the shape of the dataset
print(dx.shape)

(150, 5)


In [13]:
#seperate the target variable
X=dx.values[:,0:3]
y=dx.values[:,4]
#splitting the dataset
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
dy=DecisionTreeClassifier(criterion='entropy' ,random_state=100, max_depth=3, min_samples_leaf=3)
dy.fit(X_train,y_train)


DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=3,
                       random_state=100)

In [14]:
y_pred=dy.predict(X_test)
print(y_pred)

['Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica']


In [15]:
#we multiply by 100 so as it give answer in decimal which help to see it as percentage
print(accuracy_score(y_test,y_pred)*100)

93.33333333333333


In [21]:
dx['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [19]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[14  0  0]
 [ 0 10  1]
 [ 0  1  4]]
