predicting the species of the flower

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
# loading the library with the iris dataset
from sklearn.datasets import load_iris
#setting random seed
np.random.seed(0)





In [15]:
#features column names
features=iris.feature_names
print(features)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
#assigning data to variable iris
iris=load_iris()
#creating a dataframe with the feature variables
df=pd.DataFrame(iris.data,columns=iris.feature_names)
#view the top five rows
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
#target names
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [8]:
#adding the target column
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
#viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
#creating test and train data
df['is_train']=np.random.uniform(0, 1, len(df))<=.75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa     False  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [12]:
#craeting dataframes with test rows and training rows
train,test=df[df['is_train']==True],  df[df['is_train']==False]
print('training data',len(train))
print('testing data',len(test))

training data 114
testing data 36


In [13]:
#scaling the target variables
y=pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2], dtype=int64)

In [16]:
#creating a random forest classifier
clf=RandomForestClassifier(n_jobs=2, random_state=0)
#training the classifier
clf.fit(train[features],y)

RandomForestClassifier(n_jobs=2, random_state=0)

In [19]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [20]:
clf.predict_proba(test[features])[0:10]

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.01, 0.92, 0.07]])

In [22]:
#mapping names for the plants for each predicted plant classpreds=iris.tA
pred=iris.target_names[clf.predict(test[features])]
pred[0:15]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'versicolor'],
      dtype='<U10')

In [23]:
test['species'].head()

0     setosa
1     setosa
10    setosa
18    setosa
31    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [24]:
#creating a confusion matrix
pd.crosstab(test['species'],pred,rownames=['Actual species'],colnames=['predicted species'])

predicted species  setosa  versicolor  virginica
Actual species                                  
setosa                  9           0          0
versicolor              0          12          2
virginica               0           0         13

In [27]:
#lets have new values and see what will be predicted
pred=iris.target_names[clf.predict([[8.0,4.8,8.1,1.0],[0.9,1.0,4.0,2.0]])]
pred

array(['virginica', 'virginica'], dtype='<U10')