# rescaled data(MinMaxScaler())
it returns all values in range between 0 and 1

In [70]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv('IRIS.csv')
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [58]:
#converting from csv format to dataframe for slicing purposes
arr=df.values
arr

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [59]:
feature_range=['sepal_length','sepal_width','petal_length','petal_width']

In [67]:
#slicing the data
x=arr[:,0:4]
y=arr[:,4]
scaling=MinMaxScaler(feature_range=(0,1))
rescale_x=scaling.fit_transform(x)
numpy.set_printoptions(precision=3)
print(rescale_x[0:5,:])

[[0.222 0.625 0.068 0.042]
 [0.167 0.417 0.068 0.042]
 [0.111 0.5   0.051 0.042]
 [0.083 0.458 0.085 0.042]
 [0.194 0.667 0.068 0.042]]


# binarize data(binarize())
it is where all the values above the threshold are marked as 1 and below the threshold are marked as 0

In [85]:
from sklearn.preprocessing import Binarizer
X=arr[:,0:4]
y=arr[:,4]
scale_x=Binarizer(threshold=0.5).fit_transform(X)
numpy.set_printoptions(precision=3)
print(scale_x[0:20,:])


[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]


# standardize data(standardscaler())
it uses mean of 0 and standard deviation of 1


In [87]:
from sklearn.preprocessing import StandardScaler
X=arr[:,0:4]
y=arr[:,4]
scaled_x=StandardScaler().fit_transform(X)
numpy.set_printoptions(precision=3)
print(scaled_x[0:20,:])


[[-0.901  1.032 -1.341 -1.313]
 [-1.143 -0.125 -1.341 -1.313]
 [-1.385  0.338 -1.398 -1.313]
 [-1.507  0.106 -1.284 -1.313]
 [-1.022  1.263 -1.341 -1.313]
 [-0.537  1.958 -1.171 -1.05 ]
 [-1.507  0.801 -1.341 -1.182]
 [-1.022  0.801 -1.284 -1.313]
 [-1.749 -0.356 -1.341 -1.313]
 [-1.143  0.106 -1.284 -1.444]
 [-0.537  1.495 -1.284 -1.313]
 [-1.264  0.801 -1.228 -1.313]
 [-1.264 -0.125 -1.341 -1.444]
 [-1.87  -0.125 -1.512 -1.444]
 [-0.053  2.189 -1.455 -1.313]
 [-0.174  3.115 -1.284 -1.05 ]
 [-0.537  1.958 -1.398 -1.05 ]
 [-0.901  1.032 -1.341 -1.182]
 [-0.174  1.726 -1.171 -1.182]
 [-0.901  1.726 -1.284 -1.182]]
